# Generated by Django 4.1 on 2022-09-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description', max_length=500),
            preserve_default=False,
        ),
    ]
