# Generated by Django 4.1 on 2022-09-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_billngaddress_billingaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='apartment_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
