# Generated by Django 4.1 on 2022-11-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_payment_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='static/assets/watch1.png', upload_to=''),
            preserve_default=False,
        ),
    ]
